// ============================================================================
// NOTICES Generator — Auto-generate NOTICES/ATTRIBUTION file
// ============================================================================
//
// Most permissive licenses (MIT, Apache, BSD) require attribution — you must
// include the license text somewhere in your distributed product. Almost
// nobody does this correctly. This module generates a proper NOTICES file
// from the audit results, so Comply goes from "here's your problems" to
// "here's your problems AND here's the fix file."
// ============================================================================

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { ResolvedLicense, PolicyEvaluation } from '../types.js';

interface NoticesEntry {
  name: string;
  version: string;
  license: string;
  spdxId: string;
  requiresAttribution: boolean;
  url?: string;
}

/**
 * Generate a NOTICES / ATTRIBUTION file from audit results.
 * Includes all packages that require attribution under their license terms.
 */
export function generateNoticesFile(
  repoName: string,
  evaluations: PolicyEvaluation[],
  opts?: {
    includeAll?: boolean;    // Include even packages that don't require attribution
    format?: 'text' | 'markdown';
  }
): string {
  const format = opts?.format || 'text';
  const includeAll = opts?.includeAll || false;

  // Collect entries that need attribution
  const entries: NoticesEntry[] = [];

  for (const evaluation of evaluations) {
    const dep = evaluation.dependency;
    const license = evaluation.license.license;

    if (!includeAll && !license.requiresAttribution) continue;

    entries.push({
      name: dep.name,
      version: dep.version,
      license: license.name,
      spdxId: license.spdxId || 'Unknown',
      requiresAttribution: license.requiresAttribution,
      url: license.url,
    });
  }

  // Sort alphabetically
  entries.sort((a, b) => a.name.localeCompare(b.name));

  if (format === 'markdown') {
    return renderMarkdownNotices(repoName, entries);
  }
  return renderTextNotices(repoName, entries);
}

function renderTextNotices(repoName: string, entries: NoticesEntry[]): string {
  const lines: string[] = [];
  const divider = '='.repeat(72);
  const thinDivider = '-'.repeat(72);

  lines.push(divider);
  lines.push(`THIRD-PARTY SOFTWARE NOTICES AND INFORMATION`);
  lines.push('');
  lines.push(`Project: ${repoName}`);
  lines.push(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(`Generated by: Comply OSS (https://github.com/comply-oss/comply)`);
  lines.push('');
  lines.push(`This file contains the licenses and notices for third-party software`);
  lines.push(`included in or used by this project.`);
  lines.push(divider);
  lines.push('');

  // Group by license type for cleaner output
  const byLicense = new Map<string, NoticesEntry[]>();
  for (const entry of entries) {
    const key = entry.spdxId;
    if (!byLicense.has(key)) {
      byLicense.set(key, []);
    }
    byLicense.get(key)!.push(entry);
  }

  // Sort license groups: permissive first, then by count
  const sortedGroups = [...byLicense.entries()].sort((a, b) => {
    return b[1].length - a[1].length;
  });

  for (const [spdxId, groupEntries] of sortedGroups) {
    lines.push(thinDivider);
    lines.push(`License: ${spdxId} (${groupEntries[0].license})`);
    lines.push(`Packages: ${groupEntries.length}`);
    lines.push(thinDivider);
    lines.push('');
    lines.push('The following packages are licensed under this license:');
    lines.push('');

    for (const entry of groupEntries) {
      lines.push(`  - ${entry.name} (${entry.version})`);
    }

    lines.push('');
    lines.push(getLicenseText(spdxId));
    lines.push('');
  }

  // Summary footer
  lines.push(divider);
  lines.push(`Total packages requiring attribution: ${entries.length}`);
  lines.push(`License types: ${byLicense.size}`);
  lines.push(divider);

  return lines.join('\n');
}

function renderMarkdownNotices(repoName: string, entries: NoticesEntry[]): string {
  const lines: string[] = [];

  lines.push(`# Third-Party Software Notices`);
  lines.push('');
  lines.push(`**Project:** ${repoName}`);
  lines.push(`**Generated:** ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(`**Generated by:** [Comply OSS](https://github.com/comply-oss/comply)`);
  lines.push('');
  lines.push(`This file contains licenses and attribution notices for third-party software included in or used by this project.`);
  lines.push('');

  // Group by license type
  const byLicense = new Map<string, NoticesEntry[]>();
  for (const entry of entries) {
    const key = entry.spdxId;
    if (!byLicense.has(key)) {
      byLicense.set(key, []);
    }
    byLicense.get(key)!.push(entry);
  }

  // Table of contents
  lines.push(`## Summary`);
  lines.push('');
  lines.push(`| License | Count |`);
  lines.push(`|---------|-------|`);
  for (const [spdxId, groupEntries] of byLicense) {
    lines.push(`| ${spdxId} | ${groupEntries.length} |`);
  }
  lines.push(`| **Total** | **${entries.length}** |`);
  lines.push('');

  // Detail sections
  for (const [spdxId, groupEntries] of byLicense) {
    lines.push(`## ${spdxId} — ${groupEntries[0].license}`);
    lines.push('');
    lines.push('**Packages:**');
    lines.push('');
    for (const entry of groupEntries) {
      lines.push(`- ${entry.name} (${entry.version})`);
    }
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>License Text</summary>');
    lines.push('');
    lines.push('```');
    lines.push(getLicenseText(spdxId));
    lines.push('```');
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Save the NOTICES file to disk.
 */
export async function saveNoticesFile(
  content: string,
  outputPath: string
): Promise<void> {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
}

// ============================================================================
// License Templates — Standard license texts for common SPDX IDs
// ============================================================================

function getLicenseText(spdxId: string): string {
  const templates: Record<string, string> = {
    'MIT': `MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`,

    'ISC': `ISC License

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.`,

    'BSD-2-CLAUSE': `BSD 2-Clause "Simplified" License

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`,

    'BSD-3-CLAUSE': `BSD 3-Clause "New" or "Revised" License

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`,

    'APACHE-2.0': `Apache License, Version 2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.`,
  };

  const normalized = spdxId.toUpperCase();
  return templates[normalized] || `[Full license text for ${spdxId} available at https://spdx.org/licenses/${spdxId}.html]`;
}
